from assignment1_information_extraction import answer_question, process_data_from_input_file

process_data_from_input_file()
# answer_question('Who has a dog?')
# answer_question('Who has a cat?')
# answer_question('Who likes Joe?')
# answer_question('Who likes Bob?')
# answer_question('Who likes Joe?')
# answer_question('Who does Joe like?')
# answer_question('Who does Mary like?')
# answer_question('Who does Sally like?')
# answer_question('Who does Danny like?')
answer_question('When is Sally going to Mexico?')
answer_question('When is Sally going to Japan?')
answer_question('When is Bob going to Japan?')
answer_question('When is Joe going to Japan?')
answer_question('Who is going to Japan?')
answer_question('Who is going to China?')
answer_question('Who is going to France?')
answer_question("What's the name of Mike's dog?")
answer_question("What's the name of Mary's dog?")