from information_extraction import answer_question, process_data_from_input_file

process_data_from_input_file()
answer_question('Who has a dog?')
#answer_question('Who has a cat?')
#answer_question('Who likes Joe?')
answer_question('Who likes Mia?')
#answer_question('Does Chris like Mary?')
#answer_question('Who does Chris like?')
# answer_question('Who does Mary like?')
answer_question('Who does Mia like?')
# answer_question('Who does Danny like?')
answer_question('Who has a tiger?')
#answer_question('When is Sally visiting Mexico?')
answer_question('Who is flying to Mexico?')
answer_question('Who is flying to Peru?')
answer_question('When is Mia driving to Mexico?')

#answer_question('When is Joe going to Japan?')
#answer_question('Who is traveling to Japan?')
#answer_question('Who is flying to China?')
answer_question('Who is flying to France?')
#answer_question('Who is driving to France?')
answer_question("What's the name of Mike's dog?")
#answer_question("What's the name of Mary's cat?")
#answer_question("What's the name of Chris's dog?")